name: Gradle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Compile and Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MinecraftBetter.jar
          path: launcher/build/libs/MinecraftBetter.jar
