name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos
    name: Compile and Test code on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          build-root-directory: launcher
          arguments: |
            build
            --stacktrace
            --refresh-dependencies
      #- name: Sonarqube
      #  uses: gradle/gradle-build-action@v2
      #  with:
      #    gradle-version: 7.4
      #    build-root-directory: launcher
      #    arguments: |
      #      sonarqube
      #      --info
      - name: Gradle generate JAR
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          build-root-directory: launcher
          arguments: |
            versionbergInfo
            shadowJar
            --stacktrace

      - name: Rename file
        run: mv launcher/build/libs/MinecraftBetter.jar launcher/build/libs/MinecraftBetter-${{ matrix.name }}-.jar
      - name: Create installer
        uses: team-mst/mst-inno-setup-wrapper@v1
        if: ${{ matrix.name == 'windows' }}
        with:
          script-name: setup.iss
          working-directory: launcher
      - name: Upload JAR Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MinecraftBetter-${{ matrix.name }}-jar
          path: launcher/build/libs/MinecraftBetter-${{ matrix.name }}-.jar
      - name: Upload EXE Build Artifact
        uses: actions/upload-artifact@v3.0.0
        if: ${{ matrix.name == 'windows' }}
        with:
          name: MinecraftBetter-${{ matrix.name }}-exe
          path: launcher/build/MinecraftBetter-${{ matrix.name }}-.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            launcher/build/MinecraftBetter-${{ matrix.name }}-.exe
            launcher/build/libs/MinecraftBetter-${{ matrix.name }}-.jar
