name: Gradle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Compile and Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1
          build-root-directory: launcher
          arguments: |
            build
            --stacktrace
      - name: Gradle generate JAR
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1
          build-root-directory: launcher
          arguments: |
            shadowJar
            --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MinecraftBetter
          path: launcher/build/libs/MinecraftBetter.jar
